import test from 'node:test';
import assert from 'node:assert/strict';
import {createMatch,AuthoritativeService,MemoryRepository,EFFECTIVE_SKILLS} from './authoritative-service.mjs';
import {normalizeLayout} from './room-layout.mjs';
function fixture(){let now=1000;const m=createMatch({id:'m',creatorId:'a',createdAt:1000,slots:[{id:'A1',team:'A',slot:1,controllerId:'a'},{id:'B1',team:'B',slot:1,controllerId:'b'}]});m.preparationFlow=true;const repo=new MemoryRepository([m]),svc=new AuthoritativeService(repo,{clock:()=>now});return {repo,svc,time:n=>now=n,send:async(actor,type,args={})=>svc.command(actor,{id:crypto.randomUUID(),matchId:'m',expectedVersion:(await repo.get('m')).version,type,...args})};}
test('1v1 supports a single AI seat without admitting an allied or foreign controller',()=>{assert.equal(normalizeLayout({A1:{controller:'A1'},B1:{controller:'ai',championId:'onod'}}).B1.championId,'onod');assert.throws(()=>normalizeLayout({A1:{controller:'ai'},B1:{controller:'B1'}}));assert.throws(()=>normalizeLayout({A1:{controller:'A1'},B1:{controller:'A1'}}));});
test('shared 90 second selection starts only once all seats are filled; outsiders cannot start it',async()=>{const f=fixture();await assert.rejects(()=>f.svc.advanceAI('outsider','m'),e=>e.code==='FORBIDDEN');const m=await f.repo.get('m');m.slots.B1.controllerId=null;f.repo.matches.set('m',m);assert.equal((await f.svc.advanceAI('a','m')).preparationDeadline,undefined);m.slots.B1.controllerId='b';f.repo.matches.set('m',m);const state=await f.svc.advanceAI('a','m');assert.equal(state.preparationDeadline,91000);f.time(2000);assert.equal((await f.svc.advanceAI('b','m')).preparationDeadline,91000);});
test('all ready starts five seconds; unready cancels; concurrent expiry advances only once',async()=>{const f=fixture();await f.svc.advanceAI('a','m');for(const [actor,slotId,championId] of [['a','A1','arfeli'],['b','B1','coloso']]){await f.send(actor,'select',{slotId,championId,skills:EFFECTIVE_SKILLS[championId].slice(0,4)});await f.send(actor,'setReady',{slotId,ready:true});}assert.equal((await f.repo.get('m')).countdownDeadline,6000);await f.send('a','setReady',{slotId:'A1',ready:false});assert.equal((await f.repo.get('m')).countdownDeadline,null);await f.send('a','setReady',{slotId:'A1',ready:true});f.time(5999);assert.equal((await f.svc.advanceAI('a','m')).phase,'preparation');f.time(6000);const before=(await f.repo.get('m')).version;await Promise.all([f.svc.advanceAI('a','m'),f.svc.advanceAI('b','m')]);assert.equal((await f.repo.get('m')).phase,'deployment');assert.equal((await f.repo.get('m')).version,before+1);});
test('expiry supplies valid champion and four skills, then respects the five second presentation',async()=>{const f=fixture();await f.svc.advanceAI('a','m');f.time(91000);const state=await f.svc.advanceAI('a','m');for(const slot of Object.values(state.slots)){assert.equal(slot.ready,true);assert.equal(new Set(slot.skills).size,4);assert(slot.skills.every(id=>EFFECTIVE_SKILLS[slot.championId].includes(id)));}assert.equal(state.phase,'preparation');assert.equal(state.countdownDeadline,96000);f.time(96000);assert.equal((await f.svc.advanceAI('b','m')).phase,'deployment');});
