(()=>{'use strict';
const CFG=()=>window.LIGA_ONLINE_CONFIG||{},AUTH_KEY='liga-async-auth-v2',PENDING_KEY='liga-async-pending-finish-v2';
let auth=null,current=null,poll=null;
const app=()=>document.getElementById('app'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base=()=>String(CFG().supabaseUrl||'').replace(/\/$/,'');
const configured=()=>/^https:\/\//.test(base())&&!!CFG().publishableKey;
async function json(path,opt={}){const h={'apikey':CFG().publishableKey,'Content-Type':'application/json',...(opt.headers||{})};if(auth?.access_token)h.Authorization='Bearer '+auth.access_token;const r=await fetch(base()+path,{...opt,headers:h});const t=await r.text();let v=null;try{v=t?JSON.parse(t):null}catch{v=t}if(!r.ok)throw new Error(v?.message||v?.error_description||v?.hint||t||r.statusText);return v}
async function ensureAuth(){if(auth?.access_token)return auth;try{auth=JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch{}if(auth?.access_token)return auth;if(!configured())throw new Error('Falta configurar Supabase Lab.');auth=await json('/auth/v1/signup',{method:'POST',body:'{}'});if(!auth?.access_token)throw new Error('Supabase no devolvió una sesión anónima.');localStorage.setItem(AUTH_KEY,JSON.stringify(auth));return auth}
async function rpc(name,args={}){await ensureAuth();return json('/rest/v1/rpc/'+name,{method:'POST',body:JSON.stringify(args)})}
async function query(path){await ensureAuth();return json('/rest/v1/'+path)}
const id=()=>crypto.randomUUID?.()||('r-'+Date.now()+'-'+Math.random().toString(36).slice(2));
function shell(body){app().innerHTML='<section class="screen online-screen async-online-screen"><div class="topbar"><b>⏳ ONLINE ASÍNCRONO</b><span>Lab · 1v1 persistente</span></div><div class="async-scroll-body">'+body+'</div></section>'}
function back(){clearInterval(poll);poll=null;current=null;window.LigaOnlineBack?.()}
function home(msg=''){clearInterval(poll);poll=null;shell('<div class="online-card"><small>PARTIDAS PERSISTENTES</small><h2>Jugá cuando sea tu turno</h2><p>El combate se guarda al confirmar cada turno. Podés cerrar y volver más tarde.</p>'+(msg?'<div class="online-message">'+esc(msg)+'</div>':'')+'<div class="async-create-join"><button id="asyncCreate">CREAR PARTIDA</button><div><input id="asyncCode" maxlength="8" placeholder="CÓDIGO"><button id="asyncJoin">UNIRSE</button></div></div></div><div id="asyncMatches"></div><div class="actions"><button class="secondary" id="asyncBack">Volver</button></div>');document.getElementById('asyncCreate').onclick=create;document.getElementById('asyncJoin').onclick=()=>join(document.getElementById('asyncCode').value);document.getElementById('asyncBack').onclick=back;loadMatches()}
async function loadMatches(){const box=document.getElementById('asyncMatches');if(!box)return;try{await ensureAuth();const rows=await query('async_matches?select=id,room_code,status,state_version,active_member_id,turn_started_at,turn_deadline,waiting_deadline,updated_at&order=updated_at.desc&limit=30');if(!rows?.length){box.innerHTML='<div class="online-card"><small>No tenés partidas asíncronas todavía.</small></div>';return}box.innerHTML='<div class="online-card"><h3>Mis partidas</h3><div class="async-match-list">'+rows.map(m=>'<button data-match="'+esc(m.id)+'"><b>'+esc(m.room_code)+'</b><small>'+esc(m.status)+' · versión '+Number(m.state_version||0)+'</small></button>').join('')+'</div></div>';box.querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>open(b.dataset.match))}catch(e){box.innerHTML='<div class="online-message">'+esc(e.message)+'</div>'}}
async function create(){try{const r=await rpc('async_create_match',{p_request_id:id()});const m=Array.isArray(r)?r[0]:r;if(!m?.match_id)throw new Error('No se recibió la partida creada.');open(m.match_id)}catch(e){home(e.message)}}
async function join(code){code=String(code||'').trim().toUpperCase();if(!code)return;try{const r=await rpc('async_join_match',{p_room_code:code,p_request_id:id()});const m=Array.isArray(r)?r[0]:r;open(m?.match_id||m?.id)}catch(e){home(e.message)}}
async function open(matchId){clearInterval(poll);current={matchId};await refresh();poll=setInterval(()=>{if(!document.querySelector('.async-online-screen input:focus,.async-online-screen select:focus')&&!document.querySelector('.async-online-screen [data-skill]:checked'))refresh()},5000)}
async function getState(){const [matches,members]=await Promise.all([query('async_matches?id=eq.'+encodeURIComponent(current.matchId)+'&select=*'),query('async_members?match_id=eq.'+encodeURIComponent(current.matchId)+'&select=*&order=turn_position.asc')]);return {match:matches?.[0],members:members||[]}}
function mine(members){return members.find(x=>x.user_id===auth?.user?.id)||members.find(x=>x.player_id===auth?.user?.id)}
async function refresh(){if(!current)return;try{await rpc('async_promote_timeouts',{p_match_id:current.matchId});const s=await getState();if(!s.match)return home('La partida ya no existe.');current.state=s;renderState(s)}catch(e){shell('<div class="online-card"><div class="online-message">'+esc(e.message)+'</div></div><div class="actions"><button id="asyncHome" class="secondary">Volver</button></div>');document.getElementById('asyncHome').onclick=home}}
function roster(){return window.LigaOnlineGame?.roster?.()||[]}
function renderState({match,members}){const me=mine(members);if(!me)return home('No pertenecés a esta partida.');if(match.status==='forming'||!match.snapshot){renderPrep(match,members,me);return}if(match.status==='finished'||match.status==='expired'){shell('<div class="online-card"><h2>'+esc(match.status==='finished'?'PARTIDA FINALIZADA':'PARTIDA EXPIRADA')+'</h2><p>Sala '+esc(match.room_code)+'</p></div><div class="actions"><button id="asyncHome" class="secondary">Partidas</button></div>');document.getElementById('asyncHome').onclick=home;return}const mineTurn=match.active_member_id===me.id;const started=!!match.turn_started_at;shell('<div class="online-card"><small>SALA '+esc(match.room_code)+'</small><h2>'+(mineTurn?(started?'TURNO INICIADO':'TU TURNO'):'ESPERANDO RIVAL')+'</h2><p>Ronda '+Number(match.round_number||1)+' · Secuencia '+Number(match.turn_sequence||0)+'</p>'+(mineTurn?'<button id="asyncStart">'+(started?'CONTINUAR TURNO':'INICIAR TURNO')+'</button>':'<p>Podés cerrar la aplicación. La partida queda guardada.</p>')+'</div><div class="actions"><button id="asyncHome" class="secondary">Partidas</button></div>');document.getElementById('asyncHome').onclick=home;if(mineTurn)document.getElementById('asyncStart').onclick=()=>startTurn(match,me)}
function renderPrep(match,members,me){const r=roster(),chosen=me.champion_id||r[0]?.id,c=r.find(x=>x.id===chosen)||r[0];const load=Array.isArray(me.loadout)?me.loadout:[];shell('<div class="online-card"><small>SALA '+esc(match.room_code)+'</small><h2>PREPARACIÓN 1v1</h2><p>'+members.length+'/2 jugadores conectados</p><select id="asyncChamp">'+r.map(x=>'<option value="'+esc(x.id)+'" '+(x.id===c?.id?'selected':'')+'>'+esc(x.name)+'</option>').join('')+'</select><div class="online-skill-grid">'+(c?.abilities||[]).map(a=>'<label class="online-skill"><input type="checkbox" data-skill="'+esc(a.id)+'" '+(load.includes(a.id)?'checked':'')+'><span>'+esc(a.icon)+' '+esc(a.name)+'</span></label>').join('')+'</div><div class="online-join"><input id="asyncX" type="number" min="0" max="11" value="'+(Number.isInteger(me.deploy_x)?me.deploy_x:(me.team==='B'?10:1))+'" placeholder="X"><input id="asyncY" type="number" min="0" max="11" value="'+(Number.isInteger(me.deploy_y)?me.deploy_y:5)+'" placeholder="Y"></div><button id="asyncReady">'+(me.ready?'ACTUALIZAR':'CONFIRMAR PREPARACIÓN')+'</button>'+(members.length===2&&members.every(x=>x.ready)?'<button id="asyncInit">INICIALIZAR COMBATE</button>':'')+'</div><div class="actions"><button id="asyncHome" class="secondary">Partidas</button></div>');document.getElementById('asyncHome').onclick=home;document.getElementById('asyncChamp').onchange=async()=>{await savePrep(false);};document.getElementById('asyncReady').onclick=()=>savePrep(true);document.getElementById('asyncInit')?.addEventListener('click',()=>initialize(match,members))}
async function savePrep(ready){try{const champ=document.getElementById('asyncChamp').value,load=[...document.querySelectorAll('[data-skill]:checked')].map(x=>x.dataset.skill);if(ready&&load.length!==4)throw new Error('Elegí exactamente 4 habilidades.');await rpc('async_prepare_member',{p_match_id:current.matchId,p_champion_id:champ,p_loadout:load,p_deploy_x:Number(document.getElementById('asyncX').value),p_deploy_y:Number(document.getElementById('asyncY').value),p_ready:ready,p_request_id:id()});refresh()}catch(e){alert(e.message)}}
async function initialize(match,members){try{const latest=await getState();if(latest.match?.snapshot||latest.match?.status!=='forming'){current.state=latest;renderState(latest);return}const snap=window.LigaAsyncEngine?.buildInitial({members:latest.members,roomCode:latest.match.room_code});if(!snap)throw new Error('No se pudo construir el estado inicial.');try{await rpc('async_initialize_match',{p_match_id:latest.match.id,p_snapshot:snap,p_request_id:id()})}catch(e){if(!/already initialized/i.test(e.message||''))throw e}await refresh()}catch(e){alert(e.message)}}
async function startTurn(match,me){try{clearInterval(poll);poll=null;const latest=await getState();if(!latest.match||latest.match.active_member_id!==me.id){current.state=latest;renderState(latest);return}let m=latest.match;if(!m.turn_started_at){window.LigaAsyncEngine?.hydrate(m.snapshot,auth?.user?.id);const timeout=window.LigaAsyncEngine?.prepareTimeout?.(Number(m.turn_sequence||0));if(!timeout)throw new Error('No se pudo preparar el timeout del turno.');const r=await rpc('async_start_turn',{p_match_id:m.id,p_expected_version:Number(m.state_version),p_timeout_snapshot:timeout,p_request_id:id()});m=(Array.isArray(r)?r[0]:r)?.match||m;const s=await getState();m=s.match}window.LigaAsyncEngine?.hydrate(m.snapshot,auth?.user?.id);current.state.match=m;startCombatGuard(m.id,me.id)}catch(e){alert(e.message)}}
function startCombatGuard(matchId,memberId){clearInterval(poll);poll=setInterval(async()=>{try{if(!current||current.matchId!==matchId)return;const s=await getState();if(!s.match)return;if(s.match.active_member_id!==memberId||!s.match.turn_started_at){clearInterval(poll);poll=null;current.state=s;renderState(s)}}catch{}},1500)}
async function finish(){if(!current?.state?.match)return;const m=current.state.match;try{const snapshot=window.LigaAsyncEngine?.finalizeTurn(Number(m.turn_sequence||0));if(!snapshot)throw new Error('No se pudo serializar el turno.');const requestId=id();sessionStorage.setItem(PENDING_KEY,JSON.stringify({matchId:m.id,requestId,snapshot,version:m.state_version,hash:m.snapshot_hash}));await rpc('async_finish_turn',{p_match_id:m.id,p_expected_version:Number(m.state_version),p_expected_hash:m.snapshot_hash,p_snapshot:snapshot,p_request_id:requestId});sessionStorage.removeItem(PENDING_KEY);clearInterval(poll);poll=null;await open(m.id)}catch(e){alert(e.message)}}
window.LigaAsyncOnline={show:()=>{if(!configured())return home('Falta configurar el proyecto Supabase Lab.');home()},finish};
})();