(()=>{'use strict';
const CFG=()=>window.LIGA_ONLINE_CONFIG||{};
const PLAYER_KEY='liga-online-player-id-v1';
let session=null, socket=null, heartbeat=null, ref=0;
const app=()=>document.getElementById('app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const playerId=()=>{let id=localStorage.getItem(PLAYER_KEY);if(!id){id=(crypto.randomUUID?.()||`p-${Date.now()}-${Math.random().toString(36).slice(2)}`);localStorage.setItem(PLAYER_KEY,id)}return id};
const ready=()=>{const c=CFG();return /^https:\/\//.test(c.supabaseUrl||'')&&!String(c.supabaseUrl).includes('PEGAR_')&&c.publishableKey&&!String(c.publishableKey).includes('PEGAR_')};
const base=()=>String(CFG().supabaseUrl||'').replace(/\/$/,'');
const headers=(extra={})=>({'apikey':CFG().publishableKey,'Authorization':`Bearer ${CFG().publishableKey}`,'Content-Type':'application/json',...extra});
async function api(path,opt={}){const r=await fetch(base()+path,{...opt,headers:headers(opt.headers||{})});if(!r.ok){let m='';try{m=await r.text()}catch(_){}throw new Error(`${r.status} ${m||r.statusText}`)}if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
const code=()=>{const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>a[Math.floor(Math.random()*a.length)]).join('')};
function shell(body){app().innerHTML=`<section class="screen online-screen"><div class="topbar"><b>🌐 1v1 ONLINE · PRUEBA</b><span>Protocolo ${CFG().protocolVersion||1}</span></div>${body}</section>`}
function home(msg=''){
  cleanupRealtime();session=null;
  shell(`<div class="online-card"><small>PRIMERA PRUEBA DE CONEXIÓN</small><h2>1 PLAYER vs 1 PLAYER</h2><p>Esta prueba solamente conecta dos celulares. El combate online todavía no se inicia.</p>${msg?`<div class="online-message">${esc(msg)}</div>`:''}<div class="online-actions"><button id="onlineCreate">CREAR PARTIDA</button><div class="online-join"><input id="onlineCode" maxlength="6" autocomplete="off" placeholder="CÓDIGO"><button id="onlineJoin">UNIRSE</button></div></div><div class="online-status ${ready()?'ok':'warn'}">${ready()?'Supabase configurado · listo para probar':'Falta configurar Project URL + Publishable key'}</div></div><div class="actions"><button class="secondary" id="onlineBack">Volver</button></div>`);
  document.getElementById('onlineCreate').onclick=createMatch;
  document.getElementById('onlineJoin').onclick=()=>joinMatch(document.getElementById('onlineCode').value);
  document.getElementById('onlineCode').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);
  document.getElementById('onlineBack').onclick=()=>window.LigaOnlineBack?.();
}
function waiting(){
 const rival=!!session?.rival;
 shell(`<div class="online-card online-room"><small>SALA ONLINE</small><div class="room-code">${esc(session.roomCode)}</div><p>Compartí este código con el otro celular.</p><div class="rival-state ${rival?'connected':'waiting'}"><b>${rival?'RIVAL CONECTADO':'ESPERANDO RIVAL'}</b><small>${rival?'Equipo A y Equipo B detectados en tiempo real.':'Realtime activo · aguardando Equipo B / Slot 1'}</small></div><div class="online-slots"><span>Equipo A · Slot 1 <b>${session.team==='A'?'VOS':'PLAYER'}</b></span><span>Equipo B · Slot 1 <b>${rival||session.team==='B'?'PLAYER':'VACÍO'}</b></span></div><p class="online-note">MVP de conexión: no inicia combate.</p></div><div class="actions"><button class="secondary" id="onlineLeave">Abandonar sala</button></div>`);
 document.getElementById('onlineLeave').onclick=leave;
}
async function createMatch(){if(!ready())return home('Configurá Supabase antes de crear una sala.');try{home('Creando sala…');let room,rows;for(let i=0;i<5;i++){room=code();try{rows=await api('/rest/v1/online_matches',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({room_code:room,status:'waiting',team_size:1,protocol_version:CFG().protocolVersion||1})});break}catch(e){if(i===4)throw e}}const match=rows?.[0];if(!match?.id)throw new Error('Supabase no devolvió el id de la partida');await api('/rest/v1/online_slots',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({match_id:match.id,team:'A',slot_number:1,controller:'PLAYER',player_id:playerId(),ready:true})});session={matchId:match.id,roomCode:room,team:'A',rival:false};waiting();subscribe();await refresh()}catch(e){console.error('Online create',e);home('No se pudo crear la sala. Revisar configuración/políticas de Supabase.')}}
async function joinMatch(raw){const room=String(raw||'').trim().toUpperCase();if(!ready())return home('Configurá Supabase antes de unirte.');if(room.length<4)return home('Ingresá el código de sala.');try{home('Buscando sala…');const ms=await api(`/rest/v1/online_matches?room_code=eq.${encodeURIComponent(room)}&protocol_version=eq.${CFG().protocolVersion||1}&select=id,room_code,status,team_size,protocol_version&limit=1`);const m=ms?.[0];if(!m)throw new Error('Sala inexistente o incompatible');const slots=await api(`/rest/v1/online_slots?match_id=eq.${encodeURIComponent(m.id)}&team=eq.B&slot_number=eq.1&select=id,player_id&limit=1`);if(slots?.length&&slots[0].player_id!==playerId())throw new Error('La sala ya tiene rival');if(!slots?.length)await api('/rest/v1/online_slots',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({match_id:m.id,team:'B',slot_number:1,controller:'PLAYER',player_id:playerId(),ready:true})});await api(`/rest/v1/online_matches?id=eq.${encodeURIComponent(m.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'connected',updated_at:new Date().toISOString()})});session={matchId:m.id,roomCode:m.room_code,team:'B',rival:true};waiting();subscribe();await refresh()}catch(e){console.error('Online join',e);home(e.message.includes('incompatible')?'Sala inexistente o de otra versión.':'No se pudo entrar a la sala. Puede estar ocupada o cerrada.')}}
async function refresh(){if(!session)return;try{const slots=await api(`/rest/v1/online_slots?match_id=eq.${encodeURIComponent(session.matchId)}&controller=eq.PLAYER&select=team,slot_number,player_id,ready`);const teams=new Set((slots||[]).map(s=>s.team));const rival=session.team==='A'?teams.has('B'):teams.has('A');if(rival!==session.rival){session.rival=rival;waiting()}}catch(e){console.warn('Online refresh',e)}}
function cleanupRealtime(){if(window.__ldmOnlinePoll){clearInterval(window.__ldmOnlinePoll);window.__ldmOnlinePoll=null}if(heartbeat){clearInterval(heartbeat);heartbeat=null}if(socket){try{socket.close()}catch(_){}socket=null}}
function subscribe(){cleanupRealtime();if(session){window.__ldmOnlinePoll=setInterval(()=>{if(session)refresh()},2000);}if(!session)return;const ws=base().replace(/^http/,'ws')+`/realtime/v1/websocket?apikey=${encodeURIComponent(CFG().publishableKey)}&vsn=1.0.0`;socket=new WebSocket(ws);socket.onopen=()=>{const joinRef=String(++ref);socket.send(JSON.stringify({topic:'realtime:schema-db-changes',event:'phx_join',payload:{config:{broadcast:{self:false},presence:{key:''},postgres_changes:[{event:'*',schema:'public',table:'online_slots',filter:`match_id=eq.${session.matchId}`},{event:'UPDATE',schema:'public',table:'online_matches',filter:`id=eq.${session.matchId}`}]},access_token:CFG().publishableKey},ref:joinRef}));heartbeat=setInterval(()=>{if(socket?.readyState===1)socket.send(JSON.stringify({topic:'phoenix',event:'heartbeat',payload:{},ref:String(++ref)}))},25000)};socket.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.event==='postgres_changes')refresh()}catch(_){}};socket.onclose=()=>{if(session)setTimeout(()=>{if(session)subscribe()},1500)};socket.onerror=e=>console.warn('Realtime',e)}
async function leave(){const s=session;session=null;cleanupRealtime();if(s&&ready()){try{await api(`/rest/v1/online_slots?match_id=eq.${encodeURIComponent(s.matchId)}&player_id=eq.${encodeURIComponent(playerId())}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});const left=await api(`/rest/v1/online_slots?match_id=eq.${encodeURIComponent(s.matchId)}&controller=eq.PLAYER&select=id&limit=1`);if(!left?.length)await api(`/rest/v1/online_matches?id=eq.${encodeURIComponent(s.matchId)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});else await api(`/rest/v1/online_matches?id=eq.${encodeURIComponent(s.matchId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'waiting',updated_at:new Date().toISOString()})})}catch(e){console.warn('Online leave',e)}}home('Saliste de la sala.')}
addEventListener('pagehide',cleanupRealtime);
window.LigaOnline={show:home,leave,playerId};
})();
