-- Liga de los Mundos v0.6.38-v02
-- BLOQUE ONLINE: comandos sincronizados para Movimiento normal + Fin de turno.
-- Ejecutar UNA sola vez en Supabase SQL Editor.
-- No modifica URL, Publishable Key ni las tablas validadas previamente.

create table if not exists public.online_actions (
  seq bigint generated by default as identity primary key,
  match_id text not null,
  turn_seq bigint not null,
  actor_team text not null,
  actor_slot smallint not null,
  actor_controller text not null default 'PLAYER',
  actor_player_id text,
  action_type text not null,
  payload jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  client_action_id text not null unique,
  created_at timestamptz not null default now(),
  constraint online_actions_turn_seq_range check (turn_seq >= 1),
  constraint online_actions_actor_team_value check (actor_team in ('A','B')),
  constraint online_actions_actor_slot_range check (actor_slot between 1 and 5),
  constraint online_actions_action_type_value check (action_type in ('move','end_turn'))
);

create index if not exists online_actions_match_seq_idx
  on public.online_actions (match_id, seq);

alter table public.online_actions enable row level security;

grant select, insert, delete on table public.online_actions to anon, authenticated;
grant usage, select on sequence public.online_actions_seq_seq to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='online_actions' and policyname='online_actions_select_mvp_test'
  ) then
    create policy online_actions_select_mvp_test
      on public.online_actions for select to anon, authenticated using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='online_actions' and policyname='online_actions_insert_mvp_test'
  ) then
    create policy online_actions_insert_mvp_test
      on public.online_actions for insert to anon, authenticated with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname='public' and tablename='online_actions' and policyname='online_actions_delete_mvp_test'
  ) then
    create policy online_actions_delete_mvp_test
      on public.online_actions for delete to anon, authenticated using (true);
  end if;
end $$;

-- Realtime para comandos. El polling ~900 ms sigue funcionando como respaldo.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='online_actions'
  ) then
    alter publication supabase_realtime add table public.online_actions;
  end if;
end $$;
