import { abilityExample, exampleCaption } from './guide-examples.mjs';
import { catalog } from './catalog.mjs';
import { offlineSkillInfo } from './skill-info.mjs?v=20261009-deploy1';
import { championDefinitions, abilityDefinitions } from '../combat-core.mjs?v=20261009-deploy1';
const definitions=championDefinitions(),abilities=abilityDefinitions();
export const championProfiles={
 arfeli:{role:'Duelista · combate cercano',intro:'Encadená armas distintas para aumentar el daño y el Escudo. Puede atraer al rival o saltar hacia él.',passive:'Maestría con Armas',text:'En el mismo turno, la primera habilidad no recibe bonificación; la segunda distinta suma +1, la tercera +2 y así sucesivamente al daño o al Escudo. Moverse conserva la cadena. Repetir una habilidad reinicia la cadena sin bonificación. La cadena termina al finalizar el turno.',actions:[]},
 coloso:{role:'Defensor · control con Pilares',intro:'Usá Pilares para proteger, recuperar vida y cambiar la posición de los combatientes.',passive:'Dominio Rocoso',text:'Pilares de 15 PV: hasta 2 normalmente o 3 en Monolito. Puede crear uno por turno por 1 PA, incluso después de moverse o usar habilidades.',actions:[['Crear Pilar · 1 PA','Alcance 3; en Monolito, alcance 5. Requiere línea de visión. Una vez por turno, incluso después de moverse o usar habilidades.'],['Fusión de Pilar · 3 PA','Consume un Pilar propio adyacente, incluso en diagonal. Obtiene Escudo igual a los PV actuales del Pilar consumido, hasta el inicio del próximo turno de Coloso o hasta romperse. Coloso entra en Monolito y no puede moverse; algunas habilidades ganan alcance o nuevas opciones.'],['Reciclaje Rocoso · 0 PA','Sólo en Monolito, una vez por turno. Consume un Pilar propio; restaura a 15 PV el Pilar propio más dañado o, si no hay uno dañado, otorga 6 de Escudo a Coloso.'],['Salir de Monolito · 0 PA','Recupera los PM guardados. No puede volver a fusionarse en ese turno.']]},
 piplus:{role:'Tirador · Marca y desplazamiento',intro:'Elegí un rival como objetivo principal. La Marca mejora tus ataques y habilita tus habilidades de control.',passive:'Sistema de Marca',text:'Puede mantener un único enemigo Marcado. Marcar otro reemplaza la Marca anterior. Ruptura consume la Marca e impide volver a marcar durante ese turno.',actions:[['Marcar Objetivo · 0 PA','Alcance 4 con línea de visión, una vez por turno. No ocupa uno de los cuatro espacios de habilidad.']]},
 onod:{role:'Soporte · Brotes y Veneno',intro:'Distribuí Brotes para ampliar tus ataques y mejorar la curación de tu equipo.',passive:'Simbiosis',text:'Si Savia cura PV reales, los Brotes propios ortogonalmente adyacentes al objetivo recuperan 4 PV. Si un enemigo adyacente a un Brote recibe daño real de Veneno, ese Brote recupera la misma cantidad de PV.',actions:[['Germinar · 1 PA','Crea un Brote de 12 PV a alcance 3 con línea de visión. Hasta 2 por turno y 3 activos.'],['Marchitar · 0 PA','Retira un Brote propio sin beneficio. Una vez por turno.']]},
 korgan:{role:'Hostigador · trampas y control',intro:'Prepará el recorrido del rival con trampas y aprovechá los empujes y atracciones para activarlas.',passive:'Preparación Oculta',text:'Hasta 3 trampas activas, invisibles para el equipo rival. Se activan cuando un enemigo entra en su casilla por movimiento, salto, empuje o atracción. Después se consumen.',actions:[['Desarmar Trampa · 0 PA','Retira una trampa propia sin límite de distancia. Una vez por turno; recupera 1 PA.']]},
 houngan:{role:'Soporte · Vínculo y Muñeco',intro:'Vinculá a un aliado o un rival y usá el Muñeco para curar, reflejar daño o copiar movimientos.',passive:'Vínculo Vudú',text:'Mantiene un único personaje Vinculado. Un Vínculo nuevo reemplaza al anterior. El Muñeco conserva la asociación con la que fue creado y queda inactivo cuando deja de coincidir con el Vínculo actual.',actions:[['Muñeco Vudú · 2 PA','Requiere un Vínculo. Se coloca a alcance 3 con línea de visión; sólo uno propio activo. Enemigo: 16 PV y refleja la mitad del daño real que pierde, redondeada hacia arriba. Aliado: 20 PV y cura la mitad del daño real que pierde, redondeada hacia arriba. Después del turno de Hougan tiene una fase de movimiento de 3 PM. Crear otro reemplaza al anterior.']]}
};
const areas={vines:'Cruz de 5 casillas',grenade:'Cruz de 5 casillas',spores:'8 casillas alrededor del Brote',awakening:'4 cardinales de cada Brote',collapse:'Línea recta de 3 casillas',quake:'Objetivo adyacente, incluso diagonal; posibles Réplicas',impulse:'Trayecto recto de 1 o 2 casillas',hunterstep:'Trayecto recto de 1 o 2 casillas'};
export function guideSkills(championId){return (catalog[championId]?.skills??[]).map(skill=>({...offlineSkillInfo(championId,skill.id),id:skill.id,area:areas[skill.id]??'Un objetivo',cost:`${abilities[skill.id].cost} PA`,los:abilities[skill.id].los?'Requiere línea de visión':'No requiere línea de visión'}));}
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const portrait=id=>`../assets/champions/${id}/${id}-select.png`;
const back=()=>'';
function stat(value,label,meaning){return `<div><strong>${value}</strong><span>${label}</span><small>${meaning}</small></div>`;}
function renderGuideContent({championId=null,skillId=null}={}){
 const profile=championProfiles[championId],champion=catalog[championId];
 if(!profile)return `<section class="champion-guide" aria-label="Plantel de campeones"><div class="guide-title"><span class="eyebrow">CONOCÉ A TU EQUIPO</span><h2 tabindex="-1">Campeones</h2><p>Elegí un campeón para conocer su estilo, sus estadísticas y sus habilidades.</p></div><div class="guide-roster">${Object.entries(championProfiles).map(([id,p])=>`<button class="guide-champion" data-guide-champion="${id}"><div class="guide-portrait"><img src="${portrait(id)}" alt="" loading="lazy"></div><span><strong>${catalog[id].name}</strong><small>${p.role}</small></span><span class="guide-open">Ver ficha →</span></button>`).join('')}</div></section>`;
 const skills=guideSkills(championId),skill=skills.find(s=>s.id===skillId);
 if(skill)return `<section class="champion-guide guide-detail">${back(`Ficha de ${champion.name}`,championId)}<div class="guide-title"><span class="eyebrow">${escape(champion.name)} · HABILIDAD</span><h2 tabindex="-1">${skill.icon} ${escape(skill.name)}</h2><span class="guide-cost">${skill.cost}</span></div><dl class="guide-facts"><div><dt>Objetivo</dt><dd>${escape(skill.target)}</dd></div><div><dt>Alcance</dt><dd>${escape(skill.range)}</dd></div><div><dt>Área</dt><dd>${escape(skill.area)}</dd></div><div><dt>Visión</dt><dd>${escape(skill.los)}${championId==='piplus'&&abilities[skill.id].los?' · Fijación puede permitir ignorarla':''}</dd></div></dl><article class="guide-rules"><h3>Cómo funciona</h3>${skill.text.split(/(?<=\.)\s+/).map(t=>`<p>${escape(t)}</p>`).join('')}</article><section class="guide-example"><h3>Ejemplo en la arena</h3><p>Azul: el campeón que usa la habilidad. Rojo: el rival. Las casillas resaltadas muestran el objetivo o el área.</p><div class="guide-shots">${['before','after'].map((phase,i)=>`<figure><img src="assets/guide/${championId}-${skill.id}-${phase}.webp?v=20261009-deploy1" alt="${i?'Resultado de':'Objetivo antes de usar'} ${escape(skill.name)}" loading="lazy" width="960" height="640"><figcaption>${i?'2 · Resultado':'1 · Objetivo y situación'}</figcaption></figure>`).join('')}</div><p class="guide-example-caption">${escape(exampleCaption(abilityExample(championId,skill.id)))}</p></section></section>`;
 const d=definitions[championId];return `<section class="champion-guide">${back('Plantel')}<div class="guide-hero"><div class="guide-portrait"><img src="${portrait(championId)}" alt="${champion.name}"></div><div><span class="eyebrow">${profile.role}</span><h2 tabindex="-1">${champion.name}</h2><p>${profile.intro}</p><div class="guide-stats">${stat(d.hp,'PV','Puntos de vida')}${stat(d.pa,'PA','Puntos de acción')}${stat(d.pm,'PM','Puntos de movimiento')}${stat(d.initiative,'INI','Iniciativa')}</div></div></div><article class="guide-passive"><span class="eyebrow">PASIVA</span><h3>${profile.passive}</h3><p>${profile.text}</p></article>${profile.actions.length?`<details class="guide-actions"><summary>Acciones propias · no ocupan espacios de habilidad</summary>${profile.actions.map(([name,text])=>`<article><h3>${name}</h3><p>${text}</p></article>`).join('')}</details>`:''}<div class="guide-title"><h3>Sus seis habilidades</h3><p>En cada partida llevás cuatro. Tocá una tarjeta para ver sus reglas y un ejemplo.</p></div><div class="guide-skills">${skills.map(s=>`<button data-guide-skill="${s.id}"><span class="guide-skill-icon">${s.icon}</span><span><strong>${escape(s.name)}</strong><small>${escape(s.range)}</small></span><span class="guide-cost">${s.cost}</span><span class="guide-open">Ver detalle →</span></button>`).join('')}</div></section>`;
}
export function guidePrevious({championId=null,skillId=null}={}){return skillId&&championId?{championId}:championId?{}:null;}
export function renderGuide(state={}){return `<header class="guide-header"><button data-guide-previous aria-label="Volver">‹ Volver</button><h2>Campeones</h2><button data-guide-close>Cerrar</button></header>${renderGuideContent(state)}`;}
export function mountChampionGuide(root,{onClose=()=>{}}={}){
 let state={};const paint=(focus=false)=>{root.innerHTML=renderGuide(state);if(focus){root.querySelector('.champion-guide h2')?.focus({preventScroll:true});root.scrollIntoView({block:'start'});}};
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-guide-close')){onClose();return;}if(b.hasAttribute('data-guide-previous')){const previous=guidePrevious(state);if(previous===null){onClose();return;}state=previous;paint(true);return;}if(b.dataset.guideChampion){state={championId:b.dataset.guideChampion};paint(true);}else if(b.dataset.guideSkill){state.skillId=b.dataset.guideSkill;paint(true);}else if(b.hasAttribute('data-guide-back')){state=b.dataset.guideBack?{championId:b.dataset.guideBack}:{};paint(true);}});
 paint();return {open(championId=null,skillId=null){state={championId,skillId};paint();},close:onClose};
}
