import {prepareTutorialScene,tutorialSteps} from './tutorial.mjs';
import {LiveSession} from './session.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {createDemoAPI,tutorialHint} from './demo.mjs';import {accountAllowed} from './entry.mjs';
import {calculatePath,previewPath} from '../combat-core.mjs';
import {commandFingerprint as browserHash} from './demo/protocol.mjs';import {commandFingerprint as serverHash} from '../server/protocol.mjs';
test('entry only admits a confirmed account to the circuit',()=>{assert.equal(accountAllowed(null),false);assert.equal(accountAllowed({is_anonymous:true,email_confirmed_at:'now'}),false);assert.equal(accountAllowed({is_anonymous:false}),false);assert.equal(accountAllowed({id:'a',is_anonymous:false,email_confirmed_at:'now'}),true);});
test('browser fingerprint matches server SHA-256',async()=>{const value={id:'example',nested:{z:1,a:2},items:[4,2]};assert.equal(await browserHash(value),serverHash(value));});
test('normal demo prepares, deploys, plays and expires turns entirely in memory',async()=>{
 let now=1000;const api=createDemoAPI({clock:()=>now,random:()=>0.2});let state=(await api('create',{room:{id:crypto.randomUUID(),layout:{B1:{championId:'coloso'}}}})).data;
 const command=async(type,extra={})=>{const r=await api('command',{command:{id:crypto.randomUUID(),matchId:state.id,type,expectedVersion:state.version,...extra}});state=r.data.state;return r;};
 await command('select',{slotId:'A1',championId:'arfeli',skills:['sword','bow','shield','hammer']});await command('setReady',{slotId:'A1',ready:true});now+=5000;state=(await api('snapshot',{matchId:state.id})).data;assert.equal(state.phase,'deployment');
 const [x,y]=state.arena.deployment.A[0].split(',').map(Number);await command('setPosition',{slotId:'A1',position:{x,y}});await command('confirmPosition',{slotId:'A1'});await command('startCombat');assert.equal(state.phase,'combat');
 const serial=state.turnSerial;now+=40001;state=(await api('snapshot',{matchId:state.id})).data;assert(state.turnSerial>serial);
 await assert.rejects(api('join',{matchId:state.id}),/DEMO_ONLY/);
 const fresh=createDemoAPI();await assert.rejects(fresh('snapshot',{matchId:state.id}),/Partida inexistente/);
});
test('guided tutorial prepares and deploys, pauses deadlines, and executes real targeting types',async()=>{
 let now=1000;const api=createDemoAPI({clock:()=>now,random:()=>0.2});let state=(await api('create',{room:{id:crypto.randomUUID(),tutorial:true,layout:{B1:{championId:'arfeli'}}}})).data;
 assert.equal(state.phase,'preparation');
 const cmd=async(type,args={})=>{const reply=await api('command',{command:{id:crypto.randomUUID(),matchId:state.id,type,expectedVersion:state.version,...args}});state=reply.data.state;return reply;};
 await cmd('select',{slotId:'A1',championId:'coloso',skills:['rock','stonearmor','quake','collapse']});await cmd('setReady',{slotId:'A1',ready:true});now+=5001;state=(await api('snapshot',{matchId:state.id})).data;assert.equal(state.phase,'deployment');
 const [x,y]=state.arena.deployment.A[0].split(',').map(Number);await cmd('setPosition',{slotId:'A1',position:{x,y}});await cmd('confirmPosition',{slotId:'A1'});await cmd('startCombat');
 const scene=async(scene)=>{state=(await api('tutorialScene',{matchId:state.id,scene})).data;};
 await scene('base');const serial=state.turnSerial;now+=120000;state=(await api('snapshot',{matchId:state.id})).data;assert.equal(state.turnSerial,serial);assert.equal(state.combat.order[state.combat.turnIndex],'A1');
 const path=calculatePath(state.combat,'A1',{x:4,y:5});await cmd('move',{slotId:'A1',expectedTurn:state.turnSerial,path});assert.equal(state.combat.units.find(u=>u.id==='A1').pm,2);
 await scene('base');await cmd('ability',{slotId:'A1',expectedTurn:state.turnSerial,abilityId:'rock',targetId:'B1'});assert(state.combat.units.find(u=>u.id==='B1').hp<100);
 await scene('vision');await assert.rejects(cmd('ability',{slotId:'A1',expectedTurn:state.turnSerial,abilityId:'rock',targetId:'B1'}),/visión|BLOCKED_LOS/i);
 await scene('base');await cmd('createPillar',{slotId:'A1',expectedTurn:state.turnSerial,position:{x:5,y:6}});assert.equal(state.combat.objects.length,1);
 await scene('area');await cmd('ability',{slotId:'A1',expectedTurn:state.turnSerial,abilityId:'collapse',targetId:'pillar1',direction:{x:0,y:1}});assert(state.combat.units.find(u=>u.id==='B1').hp<100);
 await scene('area');
 const areaContext=()=>({events:{},selection:null,state,own:state.combat.units.find(u=>u.id==='A1'),enemy:state.combat.units.find(u=>u.id==='B1')});
 const areaLessons=tutorialSteps.filter(s=>['area-direction','area-confirm'].includes(s.id));
 for(const lesson of areaLessons)assert.equal(lesson.done(areaContext()),false);
 await cmd('ability',{slotId:'A1',expectedTurn:state.turnSerial,abilityId:'collapse',targetId:'pillar1',direction:{x:1,y:0}});
 assert.equal(areaContext().enemy.hp,100);assert.equal(areaContext().own.pa,3);
 for(const lesson of areaLessons)assert.equal(lesson.done(areaContext()),true,'empty-area execution must advance '+lesson.id);
 await scene('states');assert.equal(state.combat.units.find(u=>u.id==='A1').status.wound,2);
 const session=new LiveSession({api,clock:()=>now});await session.attach('demo-player',state);session.busy=true;
 const timedState=await prepareTutorialScene(session,'clock');assert.equal(session.state.turnSerial,timedState.turnSerial);assert.equal(session.remaining(),10);
 session.busy=false;const timed=session.state.turnSerial;now+=9000;await session.refresh();assert.equal(session.state.turnSerial,timed);assert.equal(session.remaining(),1);
 now+=1001;await session.refresh();state=session.state;assert(state.turnSerial>timed);
 const normal=createDemoAPI();await assert.rejects(normal('tutorialScene',{matchId:state.id,scene:'base'}),/DEMO_ONLY/);
});
