import {catalog} from './catalog.mjs?v=20261005-houganadv1';
import {safeText} from './social.mjs?v=20261008-lobby1';
export const featuredKey='live-v2-lobby-featured';
export function featuredChampion(value){return Object.hasOwn(catalog,value)?value:'arfeli';}
export function nextChampion(value,step){const ids=Object.keys(catalog);return ids[(ids.indexOf(featuredChampion(value))+step+ids.length)%ids.length];}
export function mountLobby(root,{storage,onPlay,onGuide,onSocial,onSettings}){
 let champion='arfeli';try{champion=featuredChampion(storage.getItem(featuredKey));}catch{}
 root.innerHTML=`<div class="lobby-top"><button class="lobby-profile" data-lobby="profile"><img src="../assets/champions/arfeli/arfeli-avatar.png" alt=""><span><strong id="lobby-player">Invitado</strong><small>Perfil de jugador</small></span></button><div class="lobby-title"><small>BIENVENIDO A LA ARENA</small><h2>LIGA DE LOS MUNDOS</h2></div><div class="lobby-tools"><button data-lobby="invitations">Invitaciones <span id="lobby-invitations">0</span></button><button data-lobby="settings">⚙ Ajustes</button></div></div><div class="lobby-stage"><img id="lobby-champion" alt="" draggable="false"><button class="lobby-friends" data-lobby="friends">♟<span>Amigos</span></button></div><div class="lobby-bottom"><div class="lobby-sections"><button data-lobby="champions">Campeones<small>Plantel y habilidades</small></button><button data-lobby="league">Liga<small>Pretemporada</small></button></div><div class="lobby-carousel" aria-label="Campeón destacado"><button data-lobby="previous" aria-label="Campeón anterior">‹</button><div><small>CAMPEÓN DESTACADO</small><strong id="lobby-champion-name" aria-live="polite"></strong></div><button data-lobby="next" aria-label="Campeón siguiente">›</button></div><button class="lobby-play" data-lobby="play">JUGAR<small>Crear o unirse a una sala</small></button></div><dialog class="lobby-league"><h2>Liga · Pretemporada</h2><p>Ya podés practicar y jugar partidas. La competición y la clasificación de la Liga todavía están en preparación.</p><button data-lobby="closeLeague">Volver al lobby</button></dialog>`;
 function paintChampion(){root.querySelector('#lobby-champion').src=`../assets/champions/${champion}/${champion}-combat-down-right.png`;root.querySelector('#lobby-champion').alt=catalog[champion].name;root.querySelector('#lobby-champion-name').textContent=catalog[champion].name;}
 paintChampion();
 root.addEventListener('click',event=>{const action=event.target.closest('[data-lobby]')?.dataset.lobby;if(!action)return;
 if(action==='next'||action==='previous'){champion=nextChampion(champion,action==='next'?1:-1);try{storage.setItem(featuredKey,champion);}catch{}paintChampion();}
 else if(action==='play')onPlay();else if(action==='champions')onGuide();else if(['profile','friends','invitations'].includes(action))onSocial(action);else if(action==='settings')onSettings();else if(action==='league')root.querySelector('dialog').showModal();else if(action==='closeLeague')root.querySelector('dialog').close();
 });
 return {update({profile,invitations=0,active=false}={}){root.querySelector('#lobby-player').textContent=profile?.name||'Invitado';root.querySelector('#lobby-invitations').textContent=String(invitations);root.querySelector('[data-lobby="play"]').innerHTML=active?'RETOMAR<small>Volver a tu partida</small>':'JUGAR<small>Crear o unirse a una sala</small>';}};
}
