import {catalog} from './catalog.mjs?v=20261005-houganadv1';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function playHeader(title,back='playBack'){return `<header class="play-header"><button data-action="${back}">‹ Volver</button><h2>${title}</h2><button data-action="playClose">Cerrar</button></header>`;}
export function renderPlayMenu(){return playHeader('JUGAR')+`<section class="play-intro"><h3>Elegí cómo entrar a la arena</h3><p>Prepará una partida o descubrí los próximos modos.</p></section><div class="play-modes">${[
 ['custom','Crear partida','Jugá con amigos o contra IA. Prepará tu sala a tu manera.','Crear sala'],
 ['normal','Normal','Partidas aleatorias de 1v1, 2v2 y 3v3, sin puntos de Liga.','Próximamente'],
 ['league','Liga','Competí por puntos y clasificación en cada formato.','Próximamente'],
 ['tutorial','Tutorial','Aprendé a moverte, usar habilidades y dominar la arena.','Próximamente']
].map(([id,title,description,status])=>`<button class="play-mode" data-action="playMode" data-mode="${id}"><img src="assets/play-${id}-v1.webp" alt="" loading="lazy"><span class="play-mode-copy"><strong>${title}</strong><small>${description}</small><span class="play-mode-status">${status} ${id==='custom'?'›':''}</span></span></button>`).join('')}</div>`;}
export function renderComingMode(mode){const names={normal:'Normal',league:'Liga',tutorial:'Tutorial'};return playHeader(names[mode]??'Jugar')+`<section class="panel play-coming"><img src="assets/play-${mode}-v1.webp" alt=""><h3>Próximamente</h3><p>${mode==='tutorial'?'El tutorial todavía está en preparación.':mode==='league'?'La Liga tendrá puntos y clasificaciones separadas para 1v1, 2v2 y 3v3.':'Normal permitirá entrar solo o con amigos a partidas aleatorias de 1v1, 2v2 y 3v3.'}</p><button data-action="playMode" data-mode="custom">Crear una partida</button></section>`;}
export function preparationSeconds(state,now){const deadline=state.countdownDeadline??state.preparationDeadline;return deadline==null?null:Math.max(0,Math.ceil((deadline-now)/1000));}
export function renderPreparationClock(state,now){const seconds=preparationSeconds(state,now);return `<div class="preparation-clock ${seconds!=null&&seconds<=15?'urgent':''}"><span>${state.countdownDeadline?'Entrada al despliegue':seconds==null?'Esperando jugadores':'Elegí campeón y habilidades'}</span><strong id="preparation-timer">${seconds==null?'—':state.countdownDeadline?seconds:`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`}</strong></div>`;}
export function renderTeamLobby(state,actor,{now=Date.now(),disabled=false,names={}}={}){
 const slots=Object.values(state.slots),own=slots.find(s=>s.controllerId===actor),allies=slots.filter(s=>s.team===own?.team).sort((a,b)=>(b.controllerId===actor)-(a.controllerId===actor)||a.slot-b.slot);
 return `<section class="team-lobby">${renderPreparationClock(state,now)}<h2>Tu equipo</h2><p>${state.countdownDeadline?'Todos listos. Prepará tu estrategia.':'Esperando a que ambos equipos estén listos.'}</p><div class="team-lineup">${allies.map(s=>`<article class="lineup-champion ${s.controllerId===actor?'lineup-own':''}">${s.championId?`<img src="../assets/champions/${s.championId}/${s.championId}-combat-down-right.png?v=20261008-alpha1" alt="${esc(catalog[s.championId]?.name)}">`:'<div class="lineup-empty">?</div>'}<div class="lineup-label"><small>${esc(s.controllerKind==='ai'?'IA':names[s.controllerId]??(s.controllerId===actor?'Vos':s.controllerId?'Aliado':'Esperando jugador'))}</small><h3>${esc(catalog[s.championId]?.name??'Sin selección')}</h3><span class="lineup-state">${s.ready?'✓ Listo':'Preparando'}</span><div class="lineup-skills">${(s.skills??[]).map(id=>{const skill=catalog[s.championId]?.skills.find(a=>a.id===id);return `<span title="${esc(skill?.name??id)}" aria-label="${esc(skill?.name??id)}">${skill?.icon??'◇'}</span>`;}).join('')}</div></div></article>`).join('')}</div><div class="lineup-footer"><span>${slots.filter(s=>s.ready).length}/${slots.length} campeones listos</span><button data-action="editPreparation" ${disabled?'disabled':''}>Volver a editar</button><button data-action="openFriends">Invitar amigos</button></div></section>`;
}
