import { abilityOverlay } from './ability-overlay.mjs?v=20261004-korgan1';
import { spriteSource } from './motion.mjs?v=20261004-onod1';
import { catalog } from './catalog.mjs?v=20261003-layout1';
import { movementAvailable, abilityDefinitions, pillarAvailable, colosoActionTargets, piplusMarkTargets, germinateDestinations, onodActionTargets, korganDisarmTargets } from '../combat-core.mjs?v=20261004-korgan1';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=p=>`${p.x},${p.y}`;
export const boardPoint=(x,y)=>({x:260+(x-y)*20,y:30+(x+y)*10});
const zones={A:['0,3','1,3','0,4','2,5','1,6','2,6'],B:['11,3','10,3','11,4','9,5','10,6','9,6']};
export function unitIndicators(unit) {
  return [
    ['Escudo', (unit.shield ?? []).reduce((total, shield) => total + shield.amount, 0)],
    ['Herida', unit.status?.wound ?? 0],
    ['Veneno', unit.status?.poison ?? 0],
    ['Quemadura', unit.status?.burn ?? 0],
    ['Monolito',unit.monolith?1:0],
    ['Marcado',unit.status?.markedBy?1:0],
    ['Fijación',unit.piplusFixationTargetId?1:0],
  ].filter(([, value]) => value > 0);
}
function statuses(unit) {
  return unitIndicators(unit).map(([label,value])=>`${label} ${value}`).join(' · ');
}
export function turnSequence(combat) {
  if (!combat) return [];
  const ordered = [...combat.order.slice(combat.turnIndex), ...combat.order.slice(0,combat.turnIndex)];
  return ordered.map(id=>combat.units.find(u=>u.id===id)).filter(u=>u?.alive);
}
export function renderArena({state,actor,slotId,preview,blocked,canMove,remaining,hudCollapsed=false,abilitySelection=null}) {
  const own=state.slots[slotId]??Object.values(state.slots).find(s=>s.controllerId===actor);
  const active=state.combat?.units.find(u=>u.id===state.combat.order[state.combat.turnIndex]);
  const deployment=state.phase==='deployment',finished=state.phase==='finished';
  const overlay=abilitySelection?.abilityId==='createPillar'&&canMove&&!blocked?{range:pillarAvailable(state.combat,active.id),targets:[],effect:abilitySelection.position?[abilitySelection.position]:[]}:abilitySelection&&canMove&&!blocked&&state.phase==='combat'?(['fusion','recycle'].includes(abilitySelection.abilityId)?{range:[],targets:colosoActionTargets(state.combat,active.id,abilitySelection.abilityId),effect:abilitySelection.targetId?[state.combat.objects.find(p=>p.id===abilitySelection.targetId)]:[]}:abilityOverlay(state.combat,active.id,abilitySelection.abilityId??'sword',abilitySelection.targetId,abilitySelection)):{range:[],targets:[],effect:[]};
  const rangeCells=new Map(overlay.range.map(cell=>[key(cell),cell]));
  const effectCells=new Set(overlay.effect.map(key));
  const forcedCells=new Set((overlay.forced?.moves??[]).map(move=>key(move.path.at(-1))));
  const validTargets=new Set(overlay.targets);
  const targetCells=new Set([...(state.combat?.units??[]),...(state.combat?.objects??[]),...(state.combat?.traps??[])].filter(u=>validTargets.has(u.id)).map(key));
  const reachable=canMove&&!abilitySelection?new Set(movementAvailable(state.combat,active.id).map(key)):new Set();
  const route=new Set(preview?.path.map(key)??[]),dest=preview?.path.at(-1);
  const obstacles=new Set(state.combat?.board.obstacles??['5,4','6,4','5,7','6,7']);
  let cells='';for(let y=0;y<12;y++)for(let x=0;x<12;x++){
    const p=boardPoint(x,y),k=`${x},${y}`,zone=deployment&&zones[own?.team]?.includes(k);
    const cls=['tile',rangeCells.has(k)?'ability-range':'',rangeCells.get(k)?.blocked?'ability-blocked':'',targetCells.has(k)?'ability-target':'',effectCells.has(k)?'ability-selected ability-effect':'',forcedCells.has(k)?'forced-destination':'',obstacles.has(k)?'obstacle':'',zone?'zone':'',reachable.has(k)?'reachable':'',route.has(k)?'route':'',dest&&key(dest)===k?'destination':''].join(' ');
    cells+=`<polygon class="${cls}" points="${p.x},${p.y-10} ${p.x+20},${p.y} ${p.x},${p.y+10} ${p.x-20},${p.y}" data-x="${x}" data-y="${y}" role="button" tabindex="0" aria-label="Casilla ${x}, ${y}"><title>${x}, ${y}${rangeCells.has(k)?rangeCells.get(k).blocked?" · Alcance: línea de visión bloqueada":" · Alcance de habilidad":""}${targetCells.has(k)?" · Objetivo válido":""}${effectCells.has(k)?" · Casilla afectada":""}${forcedCells.has(k)?" · Destino del desplazamiento":""}</title></polygon>`;
  }
  const trail=preview?`<polyline class="trail" points="${preview.path.map(p=>{const c=boardPoint(p.x,p.y);return `${c.x},${c.y}`;}).join(' ')}"/>`:'';
  const forcedTrail=(overlay.forced?.moves??[]).map(move=>`<polyline class="forced-trail" points="${move.path.map(p=>{const c=boardPoint(p.x,p.y);return `${c.x},${c.y}`;}).join(' ')}" marker-end="url(#forced-arrow)"/>`).join('');
  const units=state.combat?.units??Object.values(state.slots).filter(s=>s.position).map(s=>({...s,x:s.position.x,y:s.position.y,alive:true}));
  const pieces=units.filter(u=>u.alive).sort((a,b)=>(a.x+a.y)-(b.x+b.y)).map(u=>{
    const p=boardPoint(u.x,u.y);
    const indicators=statuses(u), life=u.hp == null ? '' : `<g class="piece-health" aria-label="${escape(catalog[u.championId]?.name)}: ${u.hp}/${u.maxHp} PV${indicators?`, ${escape(indicators)}`:''}"><rect x="${p.x-30}" y="${p.y-68}" width="60" height="12" rx="2"/><rect class="health-fill" x="${p.x-29}" y="${p.y-67}" width="${58*Math.max(0,Math.min(1,u.hp/u.maxHp))}" height="10" rx="1"/><text x="${p.x}" y="${p.y-59}">${u.hp}/${u.maxHp}</text>${indicators?`<text class="piece-status" x="${p.x}" y="${p.y-72}">${escape(indicators)}</text>`:''}</g>`;
    return `<g data-motion-unit="${escape(u.id)}" data-x="${u.x}" data-y="${u.y}" data-champion="${u.championId}" data-monolith="${Boolean(u.monolith)}" data-facing="${state.presentation?.facings?.[u.id]??(u.team==='B'?'up-left':'down-right')}"><ellipse class="marker" cx="${p.x}" cy="${p.y}" rx="16" ry="7" stroke="${u.controllerId===actor?'#64c6f2':'#f18b83'}"/><image class="champion-piece" href="${spriteSource(u.championId,state.presentation?.facings?.[u.id]??(u.team==='B'?'up-left':'down-right'),u.monolith)}" x="${p.x-22}" y="${p.y-53}" width="44" height="58"/>${life}</g>`;
  }).join('');
  const obstaclePieces=[...obstacles].map(tile=>{const [x,y]=tile.split(',').map(Number),p=boardPoint(x,y);return {x,y,html:`<g class="arena-obstacle" aria-label="Obstáculo de arena en ${x}, ${y}"><image href="assets/arena-block.png?v=20261004-onod1" x="${p.x-23}" y="${p.y-28}" width="46" height="38"/></g>`};}).sort((a,b)=>a.x+a.y-b.x-b.y).map(o=>o.html).join('');
  const objectPieces=(state.combat?.objects??[]).filter(o=>o.alive).map(o=>{const p=boardPoint(o.x,o.y),sprout=o.type==='sprout';return `<g class="pillar-piece" aria-label="${sprout?'Brote':'Pilar'} ${o.number}: ${o.hp}/${o.maxHp} PV"><image href="../assets/tactical/objects/${sprout?'brote-onod':'pilar-coloso'}.png" x="${p.x-20}" y="${p.y-45}" width="40" height="50"/><text x="${p.x}" y="${p.y-48}" text-anchor="middle">${o.hp}/${o.maxHp}${o.shield.length?' · Escudo '+o.shield.reduce((n,s)=>n+s.amount,0):''}</text></g>`;}).join('');
  const trapPieces=(state.combat?.traps??[]).filter(t=>t.active).map(t=>{const p=boardPoint(t.x,t.y),spikes=t.trapType==='spikes';return `<g class="korgan-trap" aria-label="${spikes?'Trampa de Pinchos':'Mina Eléctrica'} propia" opacity=".58"><image href="../assets/tactical/objects/${spikes?'trampa-korgan':'dispositivo-electrico'}.png" x="${p.x-18}" y="${p.y-29}" width="36" height="34"/></g>`;}).join('');
  function roster(mine){
    const slots=Object.values(state.slots).filter(s=>(s.team===own?.team)===mine);
    return `<aside class="live-roster ${mine?'own':'rival'}" aria-label="${mine?'Tu equipo':'Rivales'}"><h2>${mine?'TU EQUIPO':'RIVALES'}</h2>${slots.map(s=>{
      const u=units.find(u=>u.id===s.id),hp=u?.hp;
      return `<article class="roster-entry ${active?.id===s.id?'active':''}"><img src="../assets/champions/${s.championId}/${s.championId}-avatar.png" alt=""><div><strong>${escape(catalog[s.championId]?.name??'Campeón')}</strong><small>Slot ${escape(s.id)}</small>${hp!=null?`<span>${hp} PV · ${u.pa} PA · ${u.pm} PM</span><meter min="0" max="${u.maxHp}" value="${hp}" aria-label="Vida de ${escape(s.id)}"></meter>`:`<span>${s.confirmed?'Posición confirmada':'Desplegando'}</span>`}</div></article>`;
    }).join('')}</aside>`;
  }
  const selectedTarget=[...(state.combat?.units??[]),...(state.combat?.objects??[]),...(state.combat?.traps??[])].find(u=>u.id===abilitySelection?.targetId);
  const selectedAbilityId=abilitySelection?.abilityId??'sword',selectedDefinition=abilityDefinitions()[selectedAbilityId];
  const masteryBonus=active?.championId==='arfeli'&&!active.arfeliMasteryChain?.includes(selectedAbilityId)?(active.arfeliMasteryChain?.length??0):0;
  const selectedName=({fusion:'Fusión de Pilar',recycle:'Reciclaje Rocoso',piplusMark:'Marcar Objetivo',germinate:'Germinar',wither:'Marchitar',korganDisarm:'Desarmar Trampa'})[selectedAbilityId]??catalog[active?.championId]?.skills.find(s=>s.id===selectedAbilityId)?.name;
  const piplusDamage=selectedAbilityId==='precise'&&active?.markedTargetId===selectedTarget?.id?10:selectedDefinition?.damage;
  const effect=['trap_spikes','trap_mine','grenade','hook','hunterstep','korganDisarm'].includes(selectedAbilityId)?'':selectedAbilityId==='sap'?`${state.combat?.objects.some(s=>s.alive&&s.type==='sprout'&&s.ownerId===active.id&&selectedTarget&&Math.abs(s.x-selectedTarget.x)+Math.abs(s.y-selectedTarget.y)===1)?12:8} curación máxima`:selectedAbilityId==='thorn'?'6 daño + Veneno 1':selectedAbilityId==='interference'?'−1 PM próximo turno':selectedAbilityId==='fixation'?'Ignora LOS en la próxima ofensiva contra el marcado':['fusion','recycle','absorb','collapse','magnetism','piplusMark','impulse','germinate','wither','vines','spores','awakening','reabsorption'].includes(selectedAbilityId)?'':selectedAbilityId==='stonearmor'?'10 escudo':selectedAbilityId==='shield'?`${15+masteryBonus} escudo`:`${piplusDamage+masteryBonus} daño${selectedDefinition?.wound?` + Herida ${selectedDefinition.wound}`:""}`;
  const legend=overlay.range.length?'<span class="range-legend" aria-label="Referencias de alcance"><span class="range-key">Alcance</span><span class="blocked-key">LOS bloqueada</span><span class="target-key">Objetivo</span><span class="effect-key">Efecto</span></span> ':'';
  const forcedNote=overlay.forced?`${overlay.forced.moves.length?' · '+(selectedAbilityId==='hammer'?'Salto a casilla libre':selectedAbilityId==='impulse'?'Desplazamiento a destino'+(overlay.forced.moves.some(m=>m.unitId!==active.id)?' · Empuje previo de 1 casilla':''):(selectedAbilityId==='spear'?'Atracción':'Empuje')+' '+(selectedAbilityId==='vector'&&active.markedTargetId===selectedTarget?.id?2:1)+' casilla(s)'):overlay.forced.blocked.length?' · Desplazamiento bloqueado':''}${overlay.forced.damage.filter(e=>e.source.startsWith('collision.')).map(e=>` · Colisión ${e.targetId}: ${e.amount} daño`).join('')}${overlay.forced.damage.filter(e=>['wound.forced','wound.jump','wound.impulse'].includes(e.source)).map(e=>` · Herida: ${e.amount} daño`).join('')}${overlay.forced.deaths.length?' · Muerte: '+overlay.forced.deaths.join(', '):''}`:'';
  const onodNote=abilitySelection&&['germinate','vines','wither','spores','awakening','reabsorption'].includes(selectedAbilityId)?({germinate:abilitySelection.position?'Germinar: Brote de 12 PV · 1 PA. Tocá nuevamente la casilla para confirmar.':'Germinar: elegí una casilla libre a alcance 3 con LOS.',vines:abilitySelection.position?'Enredaderas: centro 6 daño, cardinales 4 · −1 PM próximo turno · 3 PA. Tocá nuevamente el centro para confirmar.':'Enredaderas: elegí el centro de la cruz a alcance 3 con LOS.',wither:abilitySelection.targetId?'Marchitar: retirar Brote sin beneficio · 0 PA. Tocá nuevamente el Brote para confirmar.':'Marchitar: elegí un Brote propio.',spores:abilitySelection.targetId?'Esporas: 8 daño + Veneno 1 en las ocho casillas marcadas · 4 PA. Tocá nuevamente el Brote para confirmar.':'Esporas: elegí cualquier Brote propio.',awakening:abilitySelection.targetId?'Despertar: 8 daño por Brote adyacente · 4 PA. Tocá nuevamente a Onod para confirmar.':'Despertar: área de todos los Brotes marcada. Tocá a Onod para seleccionar.',reabsorption:abilitySelection.targetId?'Reabsorción: retirar todos los Brotes de turnos anteriores y ganar 1 PA por cada uno. Tocá nuevamente a Onod para confirmar.':'Reabsorción: tocá a Onod para seleccionar los Brotes de turnos anteriores.'})[selectedAbilityId]:null;
  const korganNote=abilitySelection&&active?.championId==='korgan'?(
    selectedAbilityId==='trap_spikes'?(abilitySelection.position?'Trampa de Pinchos: 10 daño + Herida 1 · 2 PA. Tocá nuevamente la casilla para colocarla.':'Trampa de Pinchos: elegí una casilla libre a alcance 3 con LOS.'):
    selectedAbilityId==='trap_mine'?(abilitySelection.position?'Mina Eléctrica: 8 daño + −1 PA inmediato por cada mina pisada · 3 PA. Tocá nuevamente la casilla para colocarla.':'Mina Eléctrica: elegí una casilla libre a alcance 3 con LOS.'):
    selectedAbilityId==='grenade'?(abilitySelection.position?'Granada: centro 10 daño, laterales 6 + empuje 1 · 3 PA. Tocá nuevamente el centro para lanzar.':'Granada: elegí el centro de la cruz a alcance 3 con LOS.'):
    selectedAbilityId==='hunterstep'?(abilitySelection.position?'Paso del Cazador: desplazamiento marcado · 1 PA · sin gastar PM. Tocá nuevamente el destino para confirmar.':'Paso del Cazador: elegí 1 o 2 casillas cardinales con recorrido libre.'):
    selectedAbilityId==='hook'?(abilitySelection.targetId?'Gancho: 6 daño · elegí si atraés 1 o 2 casillas.':'Gancho: elegí un campeón enemigo a alcance 3 con LOS.'):
    selectedAbilityId==='korganDisarm'?'Desarmar Trampa: tocá una trampa propia activa · 0 PA · ganás +1 PA · 1/turno.':null
  ):null;
  const stagedNote=korganNote??onodNote??(abilitySelection?.abilityId==='impulse'?(abilitySelection.position?`Impulso: destino y recorrido marcados · 2 PA · sin gastar PM${forcedNote}. Tocá nuevamente el destino para confirmar.`:'Impulso: elegí una casilla cardinal libre a distancia 1 o 2.'):abilitySelection?.abilityId==='piplusMark'?(abilitySelection.targetId?'Marca: 0 PA. Tocá nuevamente el objetivo para confirmar.':'Marca: elegí un enemigo a alcance 4 con LOS.'): abilitySelection?.targetId&&['collapse','magnetism'].includes(selectedAbilityId)?(selectedAbilityId==='collapse'?(abilitySelection.direction?'Colapso: área marcada. Tocá nuevamente la dirección elegida para confirmar.':'Colapso: tocá una casilla cardinal junto al Pilar para elegir dirección.'):(abilitySelection.secondaryTargetId?'Magnetismo: recorrido marcado. Tocá nuevamente el combatiente para confirmar.':'Magnetismo: elegí un combatiente marcado.')):null);
  const note=stagedNote??(selectedAbilityId==='createPillar'&&abilitySelection?(abilitySelection.position?'Crear Pilar: 15 PV · 0 PA. Tocá de nuevo la misma casilla para confirmar.':'Crear Pilar: elegí una casilla libre marcada.'):abilitySelection?(selectedTarget?`${selectedName}: ${effect}${forcedNote} · ${selectedDefinition?.cost??(selectedAbilityId==='fusion'?3:0)} PA. Tocá de nuevo la misma casilla para confirmar.`:`${selectedName}: elegí un objetivo marcado. Tocá MOVER para cancelar.`):
    deployment?(own?.position?`Posición ${own.position.x}, ${own.position.y}. Tocá otra casilla marcada para cambiarla.`:'Tocá una casilla marcada de tu zona.'):
    preview?`Recorrido: ${preview.cost} PM · Placaje: ${preview.tackleDamage} PV${preview.woundDamage?` · Herida: ${preview.woundDamage} daño · PV final: ${preview.remainingHp}${preview.diesDuringPath?" · MUERTE DURANTE EL RECORRIDO":""}`:""}. Tocá de nuevo la misma casilla para mover.`:
    finished?`Ganó el equipo ${escape(state.result?.winnerTeam??'—')}.`:active?.controllerId===actor?'Tu turno: tocá una casilla para ver el recorrido.':'Esperando el turno rival.');
  const allConfirmed=Object.values(state.slots).every(s=>s.confirmed);
  const controls=deployment?`<button class="live-action" data-action="confirmPosition" ${blocked||!own?.position||own.confirmed?'disabled':''}>${own?.confirmed?'Confirmado':'Confirmar posición'}</button>${state.creatorId===actor?`<button class="live-action end-action" data-action="start" ${blocked||!allConfirmed?'disabled':''}>Iniciar combate</button>`:'<span>El creador iniciará cuando ambos confirmen.</span>'}`:
    finished?'<span>Combate finalizado</span>':`<div class="move-action" data-action="moveMode" role="button" tabindex="0" aria-label="Movimiento">MOVER<span>${active?.controllerId===actor?active.pm:'—'} PM</span></div><button class="live-action end-action" data-action="end" ${blocked||!canMove?'disabled':''}>Terminar turno</button>`;
  const turnOrder=state.combat?`<ol class="turn-order" aria-label="Orden de turnos">${turnSequence(state.combat).map((u,i)=>`<li class="${i===0?'current':''}" ${i===0?'aria-current="step"':''} title="${escape(catalog[u.championId]?.name)} · ${escape(u.id)}"><img src="../assets/champions/${u.championId}/${u.championId}-avatar.png" alt="${escape(catalog[u.championId]?.name)}"><span>${i+1} · ${escape(catalog[u.championId]?.name)}<small>${escape(u.id)}</small></span></li>`).join('')}</ol>`:'';
  const championCard=active?`<div class="active-champion" aria-label="Campeón activo"><img src="../assets/champions/${active.championId}/${active.championId}-avatar.png" alt=""><div class="active-details"><strong>${escape(catalog[active.championId]?.name)} · ${escape(active.id)}</strong><div class="active-life"><meter min="0" max="${active.maxHp}" value="${active.hp}" aria-label="Vida del campeón activo"></meter><span>${active.hp}/${active.maxHp} PV</span></div><div class="active-resources"><span>${active.pa} PA</span><span>${active.pm} PM</span><span>Escudo ${(active.shield??[]).reduce((n,s)=>n+s.amount,0)}</span></div>${unitIndicators(active).filter(([label])=>label!=='Escudo').length?`<small>${escape(unitIndicators(active).filter(([label])=>label!=='Escudo').map(([label,value])=>`${label} ${value}`).join(' · '))}</small>`:''}</div></div>`:'';
  const skillButtons=active?`<div class="combat-skills" aria-label="Habilidades seleccionadas">${(state.slots[active.id]?.skills??[]).map(id=>{const skill=catalog[active.championId]?.skills.find(s=>s.id===id);const def=abilityDefinitions()[id],enabled=state.phase==='combat'&&def?.championId===active.championId;const uses=active.skillUsesThisTurn?.[id]??0;const chosen=abilitySelection&&(abilitySelection.abilityId??'sword')===id;return `<button class="combat-skill ${enabled&&chosen?'selected-skill':''}" ${enabled?`data-action="${id}"`:''} ${!enabled||blocked||!canMove||active.pa<(def?.cost??0)||(def?.maxUses&&uses>=def.maxUses)?'disabled':''} title="${enabled?`${def.cost} PA · Alcance ${def.range}`:'Todavía no disponible'}" aria-label="${escape(skill?.name??id)}${enabled?'':': todavía no disponible'}" ${enabled?`aria-pressed="${Boolean(chosen)}"`:''}><span class="skill-meta">${enabled&&def.maxUses?`${uses}/${def.maxUses}`:!enabled&&skill?.maxUsesPerTurn?`Máx. ${skill.maxUsesPerTurn}`:""}<b>${skill?.cost??"—"} PA</b></span><span class="skill-symbol" aria-hidden="true">${escape(skill?.icon??"✦")}</span><span class="skill-name">${escape(skill?.name??id)}</span></button>`;}).join('')}</div>`:'';
  const korganControls=active?.championId==='korgan'&&state.phase==='combat'?`<details class="coloso-options" open><summary>Preparación Oculta · ${state.combat.traps.filter(t=>t.active&&t.ownerId===active.id).length}/3 Trampas</summary><button class="live-action" data-action="korganDisarm" ${blocked||!canMove||!korganDisarmTargets(state.combat,active.id).length?'disabled':''}>Desarmar Trampa · 0 PA · +1 PA</button>${abilitySelection?.abilityId==='hook'&&abilitySelection.targetId?`<button class="live-action" data-action="hookPull1" ${blocked||!canMove?'disabled':''}>Atraer 1</button><button class="live-action" data-action="hookPull2" ${blocked||!canMove?'disabled':''}>Atraer 2</button>`:''}</details>`:'';
  const pending=blocked?'Esperando confirmación o conexión…':'Estado confirmado';
  return `<section class="live-battle" aria-label="Arena Central"><div class="arena-stage"><img class="arena-platform" src="../assets/arenas/central/arena-central-base.png" alt=""><svg class="live-board" viewBox="0 0 520 280" aria-label="Tablero 12 por 12"><defs><marker id="forced-arrow" markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5" fill="#d6adff"/></marker></defs>${cells}${trail}${forcedTrail}${obstaclePieces}${objectPieces}${trapPieces}${pieces}</svg></div>
    <div class="live-round"><div class="round-summary"><span>${deployment?'DESPLIEGUE':finished?'RESULTADO':`RONDA ${state.combat.round}`}</span><strong>${active?escape(catalog[active.championId]?.name):'Arena Central'}</strong>${!deployment&&!finished?`<span class="timer" id="timer">${remaining}</span>`:''}</div>${turnOrder}</div>
    ${roster(true)}${roster(false)}
    <div class="live-command ${hudCollapsed?'collapsed':''}"><button class="hud-fold" data-action="toggleHud" aria-label="${hudCollapsed?'Expandir controles':'Plegar controles'}" aria-expanded="${!hudCollapsed}">${hudCollapsed?'+':'−'}</button><div class="command-main">${championCard}${skillButtons}<div class="command-controls">${active?.championId==='coloso'&&state.phase==='combat'?`<button class="live-action pillar-action" data-action="createPillar" ${blocked||!canMove||!pillarAvailable(state.combat,active.id).length?'disabled':''}>Crear Pilar · 0 PA</button>`:''}${active?.championId==='coloso'&&state.phase==='combat'?`<details class="coloso-options"><summary>Dominio Rocoso${active.monolith?' · Monolito':''}</summary>${[active.monolith?'exit':'fusion',...(active.monolith?['recycle']:[])].map(action=>`<button class="live-action" data-action="${action}" ${blocked||!canMove||!colosoActionTargets(state.combat,active.id,action).length?'disabled':''}>${({fusion:'Fusión · 3 PA',exit:'Salir · 0 PA',recycle:'Reciclaje · 0 PA'})[action]}</button>`).join('')}</details>`:''}${active?.championId==='piplus'&&state.phase==='combat'?`<button class="live-action pillar-action" data-action="piplusMark" ${blocked||!canMove||!piplusMarkTargets(state.combat,active.id).length?'disabled':''}>Marcar · 0 PA${active.markedTargetId?' · '+escape(state.combat.units.find(t=>t.id===active.markedTargetId&&t.alive)?.name??'Sin objetivo vivo'):''}</button>`:''}${active?.championId==='onod'&&state.phase==='combat'?`<details class="coloso-options"><summary>Simbiosis · ${state.combat.objects.filter(o=>o.alive&&o.type==='sprout'&&o.ownerId===active.id).length}/3 Brotes</summary><button class="live-action" data-action="germinate" ${blocked||!canMove||!germinateDestinations(state.combat,active.id).length?'disabled':''}>Germinar · 1 PA · ${active.onodGerminateUses}/2</button><button class="live-action" data-action="wither" ${blocked||!canMove||!onodActionTargets(state.combat,active.id,'wither').length?'disabled':''}>Marchitar · 0 PA</button></details>`:''}${korganControls}${controls}</div></div><div class="command-feedback"><p class="board-note">${legend}${note}</p><span class="phase-text" id="pending">${pending}</span></div></div></section>`;
}
