export function confirmedAccount(user){return Boolean(user&&!user.is_anonymous&&user.email_confirmed_at);}
export function safeText(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export class SocialPanel {
 constructor({client,host,notify,onJoin,room}){Object.assign(this,{client,host,notify,onJoin,room});this.data=null;this.user=null;this.open=false;this.busy=false;this.recovery=false;}
 async refresh(){const {data}=await this.client.auth.getSession();this.user=data.session?.user??null;if(confirmedAccount(this.user)){const {data,error}=await this.client.rpc('live_v2_social',{p_action:'list'});if(error)throw error;this.data=data;}else this.data=null;this.paint();}
 async call(action,args={}){const {data,error}=await this.client.rpc('live_v2_social',{p_action:action,p_args:args});if(error)throw error;return data;}
 paint(){const e=safeText;const html=`<button data-social="toggle">Perfil y amigos${this.data?.invitations?.length?` · ${this.data.invitations.length} invitaciones`:''}</button>${this.open?`<section class="panel social-panel"><h2>Mi perfil y amigos</h2>${this.body(e)}<p role="status">${e(this.message??'')}</p></section>`:''}`;if(html!==this.lastHtml){this.host.innerHTML=html;this.lastHtml=html;}this.host.querySelectorAll('button').forEach(b=>b.disabled=this.busy);}
 body(e){if(this.recovery)return `<form data-form="newPassword"><label>Nueva contraseña <input name="password" type="password" minlength="8" required autocomplete="new-password"></label><button>Guardar contraseña</button></form>`;
 if(!confirmedAccount(this.user))return `<p>Podés seguir jugando como invitado. Una cuenta confirmada permite recuperar tu perfil y agregar amigos.</p><form data-form="register"><h3>Crear cuenta</h3><label>Correo <input name="email" type="email" required autocomplete="email"></label><label>Contraseña <input name="password" type="password" minlength="8" required autocomplete="new-password"></label><button>Registrarme</button></form><form data-form="login"><h3>Entrar a mi cuenta</h3><label>Correo <input name="email" type="email" required autocomplete="email"></label><label>Contraseña <input name="password" type="password" required autocomplete="current-password"></label><button>Entrar</button></form><form data-form="reset"><label>Correo para recuperar acceso <input name="email" type="email" required></label><button>Recuperar contraseña</button></form><p>Para recibir confirmaciones en correos de amigos hay que completar la configuración de envío.</p>`;
 const d=this.data??{friends:[],invitations:[]},r=this.room();return `<p>${e(this.user.email)}</p><form data-form="profile"><label>Nombre de jugador <input name="name" minlength="3" maxlength="24" required value="${e(d.profile?.name)}"></label><button>Guardar perfil</button></form>${d.profile?`<p>Tu código de amigo: <strong>${e(d.profile.code)}</strong></p><form data-form="request"><label>Código de amigo <input name="code" maxlength="12" required></label><button>Agregar amigo</button></form><h3>Amigos y solicitudes</h3>${d.friends.map(f=>`<article class="social-row"><strong>${e(f.name)}</strong><span>${f.status==='accepted'?'Amigo':f.incoming?'Solicitud recibida':'Solicitud enviada'}</span>${f.status==='pending'&&f.incoming?`<button data-social="acceptFriend" data-id="${e(f.id)}">Aceptar</button>`:''}<button data-social="removeFriend" data-id="${e(f.id)}">${f.status==='accepted'?'Eliminar amigo':'Cancelar / rechazar'}</button>${f.status==='accepted'&&r?.phase==='preparation'&&r.slots.A1.controllerId===this.user.id?`<form data-form="invite" data-id="${e(f.id)}"><label>Puesto <select name="slot">${Object.values(r.slots).filter(s=>!s.controllerId).map(s=>`<option value="${s.id}">${s.id} · Equipo ${s.team}</option>`).join('')}</select></label><button>Invitar a esta sala</button></form>`:''}</article>`).join('')||'<p>Todavía no agregaste amigos.</p>'}`:''}<h3>Invitaciones a partidas</h3>${d.invitations.map(i=>`<article class="social-row"><strong>${e(i.name)}</strong><span>Puesto ${e(i.slot)}</span><button data-social="acceptInvite" data-id="${e(i.id)}">Aceptar partida</button><button data-social="declineInvite" data-id="${e(i.id)}">Rechazar partida</button></article>`).join('')||'<p>No hay invitaciones pendientes.</p>'}<button data-social="logout">Cerrar sesión</button>`;}
 bind(){this.host.addEventListener('click',async event=>{const b=event.target.closest('[data-social]');if(!b||this.busy)return;const action=b.dataset.social;if(action==='toggle'){this.open=!this.open;this.paint();if(this.open)await this.run(()=>this.refresh());return;}await this.run(async()=>{if(action==='logout'){this.guardRoom();const {error}=await this.client.auth.signOut();if(error)throw error;localStorage.removeItem('live-v2-lab2-match');location.href=location.pathname;return;}if(action==='acceptInvite'){this.guardRoom();const reply=await this.call(action,{id:b.dataset.id});await this.onJoin(reply.matchId);}else await this.call(action,{id:b.dataset.id});await this.refresh();});});
 this.host.addEventListener('submit',async event=>{const f=event.target.closest('[data-form]');if(!f)return;event.preventDefault();if(this.busy)return;const values=Object.fromEntries(new FormData(f));await this.run(async()=>{const type=f.dataset.form;let result;const redirect=location.origin+location.pathname;
 if(type==='register'){this.guardRoom();if(this.user?.is_anonymous){result=await this.client.auth.updateUser({email:values.email,password:values.password},{emailRedirectTo:redirect});}else result=await this.client.auth.signUp({email:values.email,password:values.password,options:{emailRedirectTo:redirect}});if(result.error)throw result.error;this.message='Revisá tu correo para confirmar la cuenta.';}
 else if(type==='login'){this.guardRoom();result=await this.client.auth.signInWithPassword(values);if(result.error)throw result.error;localStorage.removeItem('live-v2-lab2-match');history.replaceState(null,'',location.pathname);location.reload();return;}
 else if(type==='reset'){result=await this.client.auth.resetPasswordForEmail(values.email,{redirectTo:redirect});if(result.error)throw result.error;this.message='Si el correo tiene una cuenta, recibirás las instrucciones.';}
 else if(type==='newPassword'){result=await this.client.auth.updateUser({password:values.password});if(result.error)throw result.error;this.recovery=false;this.message='Contraseña actualizada.';}
 else if(type==='invite'){await this.call('invite',{id:f.dataset.id,matchId:this.room().id,slot:values.slot});this.message='Invitación enviada.';}
 else {await this.call(type,values);this.message=type==='profile'?'Perfil guardado.':'Solicitud enviada.';}
 await this.refresh();});});}
 guardRoom(){if(this.room()&&this.room().phase!=='finished')throw new Error('Primero terminá o abandoná tu partida actual.');}
 async run(work){this.busy=true;try{await work();}catch(error){const messages={ACCOUNT_REQUIRED:'Confirmá tu correo para usar amigos.',PLAYER_NOT_FOUND:'No encontramos ese código de amigo.',FRIEND_REQUIRED:'Primero deben aceptar la solicitud de amistad.',INVITE_EXPIRED:'La invitación venció.',SLOT_TAKEN:'El puesto ya está ocupado.',INVALID_NAME:'Usá un nombre de 3 a 24 caracteres.',PROFILE_REQUIRED:'Guardá primero tu nombre de jugador.'};this.message=messages[error.message]??error.message;this.notify(this.message);}finally{this.busy=false;this.paint();}}
}
