export function confirmedAccount(user){return Boolean(user&&!user.is_anonymous&&user.email_confirmed_at);}
export function safeText(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export class SocialPanel {
 constructor({client,host,notify,onJoin,room,onChange}){Object.assign(this,{client,host,notify,onJoin,room,onChange});this.data=null;this.user=null;this.open=false;this.busy=false;this.recovery=false;this.view="profile";}
 async refresh(){const {data}=await this.client.auth.getSession();this.user=data.session?.user??null;if(confirmedAccount(this.user)){const {data,error}=await this.client.rpc('live_v2_social',{p_action:'list'});if(error)throw error;this.data=data;}else this.data=null;this.paint();}
 async call(action,args={}){const {data,error}=await this.client.rpc('live_v2_social',{p_action:action,p_args:args});if(error)throw error;return data;}
 show(view='profile'){this.view=['profile','friends','invitations','account'].includes(view)?view:'profile';this.open=true;this.paint();return this.run(()=>this.refresh());}
 paint(){const e=safeText;const titles={profile:'Perfil',friends:'Amigos',invitations:'Invitaciones',account:'Cuenta'};const html=this.open?`<section class="profile-screen" aria-label="${titles[this.view]}"><header class="profile-header"><button data-social="back" aria-label="Volver">‹ Volver</button><h2>${titles[this.view]}</h2><button data-social="toggle">Cerrar</button></header>${this.body(e)}<p class="profile-status" role="status">${e(this.message??'')}</p></section>`:'<button data-social="toggle">Perfil</button>';if(html!==this.lastHtml){this.host.innerHTML=html;this.lastHtml=html;}this.host.querySelectorAll('button').forEach(b=>b.disabled=this.busy);this.onChange?.();}
 body(e){if(this.recovery||this.view==='account')return `<section class="profile-content panel">${this.accountBody(e)}</section>`;
 if(this.view==='friends'||this.view==='invitations'){if(!confirmedAccount(this.user))return `<section class="profile-content panel"><p>Iniciá sesión y confirmá tu cuenta para acceder a ${this.view==='friends'?'tus amigos':'las invitaciones'}.</p><button data-social="account">Abrir cuenta</button></section>`;return `<section class="profile-content panel">${this.socialBody(e)}</section>`;}
 const profile=this.data?.profile;return `<div class="profile-layout"><aside class="profile-identity"><img class="profile-avatar" src="../assets/champions/arfeli/arfeli-avatar.png" alt="Avatar de Arfeli"><h3>${e(profile?.name||'Tu perfil')}</h3>${confirmedAccount(this.user)?`<form data-form="profile"><label>Nombre de jugador<input name="name" minlength="3" maxlength="24" required value="${e(profile?.name)}" autocomplete="nickname"></label><button>Guardar nombre</button></form>`:'<p>Iniciá sesión para guardar tu identidad de jugador.</p>'}<p class="profile-code-label">Código de jugador</p><div class="profile-code"><strong>${e(profile?.code||'—')}</strong>${profile?.code?'<button data-social="copyCode" aria-label="Copiar código de jugador">Copiar</button>':''}</div><nav aria-label="Accesos del perfil"><button data-social="friends">Amigos</button><button data-social="invitations">Invitaciones${this.data?.invitations?.length?` · ${this.data.invitations.length}`:''}</button><button data-social="account">Cuenta</button></nav></aside><div class="profile-details"><section class="profile-summary"><h3>Resumen de combates</h3><div class="profile-stats">${['Partidas','Victorias','Derrotas'].map(label=>`<div><span>${label}</span><strong>—</strong></div>`).join('')}</div><p>Las estadísticas de combate todavía no están disponibles.</p></section><section class="profile-history"><h3>Historial de partidas</h3><div class="profile-empty"><span aria-hidden="true">✧</span><p>El historial todavía no está disponible.</p></div></section></div></div>`;}
 socialBody(e){const d=this.data??{friends:[],invitations:[]},r=this.room();if(this.view==='invitations')return d.invitations.map(i=>`<article class="social-row"><strong>${e(i.name)}</strong><span>Puesto ${e(i.slot)}</span><button data-social="acceptInvite" data-id="${e(i.id)}">Aceptar partida</button><button data-social="declineInvite" data-id="${e(i.id)}">Rechazar partida</button></article>`).join('')||'<p>No hay invitaciones pendientes.</p>';
 return `${d.profile?`<form data-form="request"><label>Código de amigo<input name="code" maxlength="12" required></label><button>Agregar amigo</button></form>`:'<p>Guardá primero tu nombre en Perfil para agregar amigos.</p>'}${d.friends.map(f=>`<article class="social-row"><strong>${e(f.name)}</strong><span>${f.status==='accepted'?'Amigo':f.incoming?'Solicitud recibida':'Solicitud enviada'}</span>${f.status==='pending'&&f.incoming?`<button data-social="acceptFriend" data-id="${e(f.id)}">Aceptar</button>`:''}<button data-social="removeFriend" data-id="${e(f.id)}">${f.status==='accepted'?'Eliminar amigo':'Cancelar / rechazar'}</button>${f.status==='accepted'&&r?.phase==='preparation'&&r.slots.A1.controllerId===this.user.id?`<form data-form="invite" data-id="${e(f.id)}"><label>Puesto<select name="slot">${Object.values(r.slots).filter(s=>!s.controllerId).map(s=>`<option value="${s.id}">${s.id} · Equipo ${s.team}</option>`).join('')}</select></label><button>Invitar a esta sala</button></form>`:''}</article>`).join('')||'<p>Todavía no agregaste amigos.</p>'}`;}
 accountBody(e){if(this.recovery)return `<form data-form="newPassword"><label>Nueva contraseña <input name="password" type="password" minlength="8" required autocomplete="new-password"></label><button>Guardar contraseña</button></form>`;
 if(!confirmedAccount(this.user))return `<p>Una cuenta confirmada permite guardar tu perfil y agregar amigos.</p><form data-form="register"><h3>Crear cuenta</h3><label>Correo <input name="email" type="email" required autocomplete="email"></label><label>Contraseña <input name="password" type="password" minlength="8" required autocomplete="new-password"></label><button>Registrarme</button></form><form data-form="login"><h3>Entrar a mi cuenta</h3><label>Correo <input name="email" type="email" required autocomplete="email"></label><label>Contraseña <input name="password" type="password" required autocomplete="current-password"></label><button>Entrar</button></form><form data-form="reset"><label>Correo para recuperar acceso <input name="email" type="email" required></label><button>Recuperar contraseña</button></form>`;
 return `<p>Cuenta: ${e(this.user.email)}</p><button data-social="logout">Cerrar sesión</button>`;}

 bind(){this.host.addEventListener('click',async event=>{const b=event.target.closest('[data-social]');if(!b||this.busy)return;const action=b.dataset.social;if(['profile','friends','invitations','account'].includes(action)){this.view=action;this.paint();return;}if(action==='back'){if(this.view==='profile')this.open=false;else this.view='profile';this.paint();return;}if(action==='copyCode'){await this.run(async()=>{await navigator.clipboard.writeText(this.data.profile.code);this.message='Código copiado.';});return;}if(action==='toggle'){this.open=!this.open;this.paint();if(this.open)await this.run(()=>this.refresh());return;}await this.run(async()=>{if(action==='logout'){this.guardRoom();const {error}=await this.client.auth.signOut();if(error)throw error;localStorage.removeItem('live-v2-lab2-match');location.href=location.pathname;return;}if(action==='acceptInvite'){this.guardRoom();const reply=await this.call(action,{id:b.dataset.id});await this.onJoin(reply.matchId);}else await this.call(action,{id:b.dataset.id});await this.refresh();});});
 this.host.addEventListener('submit',async event=>{const f=event.target.closest('[data-form]');if(!f)return;event.preventDefault();if(this.busy)return;const values=Object.fromEntries(new FormData(f));await this.run(async()=>{const type=f.dataset.form;let result;const redirect=location.origin+location.pathname;
 if(type==='register'){this.guardRoom();if(this.user?.is_anonymous){result=await this.client.auth.updateUser({email:values.email,password:values.password},{emailRedirectTo:redirect});}else result=await this.client.auth.signUp({email:values.email,password:values.password,options:{emailRedirectTo:redirect}});if(result.error)throw result.error;this.message='Revisá tu correo para confirmar la cuenta.';}
 else if(type==='login'){this.guardRoom();result=await this.client.auth.signInWithPassword(values);if(result.error)throw result.error;localStorage.removeItem('live-v2-lab2-match');history.replaceState(null,'',location.pathname);location.reload();return;}
 else if(type==='reset'){result=await this.client.auth.resetPasswordForEmail(values.email,{redirectTo:redirect});if(result.error)throw result.error;this.message='Si el correo tiene una cuenta, recibirás las instrucciones.';}
 else if(type==='newPassword'){result=await this.client.auth.updateUser({password:values.password});if(result.error)throw result.error;this.recovery=false;this.message='Contraseña actualizada.';}
 else if(type==='invite'){await this.call('invite',{id:f.dataset.id,matchId:this.room().id,slot:values.slot});this.message='Invitación enviada.';}
 else {await this.call(type,values);this.message=type==='profile'?'Perfil guardado.':'Solicitud enviada.';}
 await this.refresh();});});}
 guardRoom(){if(this.room()&&this.room().phase!=='finished')throw new Error('Primero terminá o abandoná tu partida actual.');}
 async run(work){this.busy=true;try{await work();}catch(error){const messages={ACCOUNT_REQUIRED:'Confirmá tu correo para usar amigos.',PLAYER_NOT_FOUND:'No encontramos ese código de amigo.',FRIEND_REQUIRED:'Primero deben aceptar la solicitud de amistad.',INVITE_EXPIRED:'La invitación venció.',SLOT_TAKEN:'El puesto ya está ocupado.',INVALID_NAME:'Usá un nombre de 3 a 24 caracteres.',PROFILE_REQUIRED:'Guardá primero tu nombre de jugador.'};this.message=messages[error.message]??error.message;this.notify(this.message);}finally{this.busy=false;this.paint();}}
}
