// Browser demo uses the exact authoritative rules, with an in-memory repository.
import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);
let protocol=await readFile(new URL('server/protocol.mjs',root),'utf8');
protocol=protocol.replace('import { createHash } from "node:crypto";','const hash = async value => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))),x=>x.toString(16).padStart(2,"0")).join("");');
protocol=protocol.replace(/export function (commandFingerprint|stateFingerprint)/g,'export async function $1').replace(/return createHash\("sha256"\)\s*\.update\((JSON.stringify\(canonical\(\w+\)\))\)\s*\.digest\("hex"\);/g,'return hash($1);');
let service=await readFile(new URL('server/authoritative-service.mjs',root),'utf8');
service=service.replace("import { randomUUID } from 'node:crypto';","const randomUUID=()=>crypto.randomUUID();").replace(/(['"])\.\.\//g,'$1../../').replace("'./ai.mjs'","'../../server/ai.mjs?v=20261010-3v3-1'").replace("'../../combat-core.mjs'","'../../combat-core.mjs?v=20261010-3v3-1'").replace('const fingerprint = commandFingerprint(input);','const fingerprint = await commandFingerprint(input);').replace(/stateFingerprint\(([^\n;]+)\)/g,'await stateFingerprint($1)');
const banner='// Generated by scripts/build-demo.mjs; regenerate after changing authority or protocol.\n';
await writeFile(new URL('client/demo/protocol.mjs',root),banner+protocol);
await writeFile(new URL('client/demo/authority.mjs',root),banner+service);
