// Generated by scripts/build-demo.mjs; regenerate after changing authority or protocol.
const hash = async value => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))),x=>x.toString(16).padStart(2,"0")).join("");
export class ProtocolError extends Error {
  constructor(code, message) {
    super(message);
    this.name = "ProtocolError";
    this.code = code;
  }
}
export const phases = ["preparation", "deployment", "combat", "finished"];
export const commandTypes = [
  "preparationTick",
  "deploymentTick",
  "aiStep",
  "select",
  "setReady",
  "setPosition",
  "confirmPosition",
  "startCombat",
  "ability",
  "createPillar",
  "colosoAction",
  "piplusMark",
  "onodAction",
  "korganAction",
  "houganAction",
  "houganDollMove",
  "houganDollEnd",
  "move",
  "endTurn",
  "expireTurn",
  "abandon",
];
export function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (value && typeof value === "object")
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((k) => [k, canonical(value[k])]),
    );
  return value;
}
export async function commandFingerprint(command) {
  return hash(JSON.stringify(canonical(command)));
}
export async function stateFingerprint(state) {
  return hash(JSON.stringify(canonical(state)));
}
export function validateCommand(c) {
  if (
    !c ||
    typeof c.id !== "string" ||
    !c.id ||
    typeof c.matchId !== "string" ||
    !commandTypes.includes(c.type) ||
    !Number.isInteger(c.expectedVersion) ||
    c.expectedVersion < 0
  )
    throw new ProtocolError("INVALID_COMMAND", "Contrato de comando inválido");
  if (
    ["move", "endTurn", "ability", "createPillar", "colosoAction", "piplusMark", "onodAction", "korganAction", "houganAction", "houganDollMove", "houganDollEnd"].includes(c.type) &&
    (!Number.isInteger(c.expectedTurn) || c.expectedTurn < 0)
  )
    throw new ProtocolError("INVALID_COMMAND", "Falta turno esperado");
  return c;
}

